version: '2'

services:
  django: # django app
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: speakeazy_django
    user: django
    env_file: dev.env
    tmpfs: /logs
    volumes:
      - ./speakeazy.db:/app/speakeazy.db
      - ./recordings/:/app/recordings/
      - ./speakeazy/media/:/app/speakeazy/media/

  nginx: # reverse proxy
    build:
      context: ./compose/nginx/dev
      dockerfile: Dockerfile-dev
    links:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  # part of speakeazy/server
  celeryworker: # runs tasks
    image: speakeazy_django
    user: django
    env_file: dev.env
    tmpfs: /logs
    volumes:
      - ./speakeazy.db:/app/speakeazy.db
    command: celery -A speakeazy.taskapp worker -l INFO

  # part of speakeazy/server
  celerybeat: # aruns scheduled tasks
    image: speakeazy_django
    user: django
    env_file: dev.env
    tmpfs: /logs
    volumes:
      - ./speakeazy.db:/app/speakeazy.db
    command: celery -A speakeazy.taskapp beat -l INFO
