#postgres:
#  image: postgres:9.4
#  volumes:
#    - /data/speakeazy/postgres:/var/lib/postgresql/data
#  env_file: .env

django: # django app
  build: .
  user: django
  links:
    - redis
  command: /gunicorn.sh
  env_file: .env

nginx: # reverse proxy
  build: ./compose/nginx
  links:
    - django
  ports:
    - "0.0.0.0:80:80"

redis:
  image: redis:3.0

celeryworker: # runs tasks
  build: .
  user: django
  env_file: .env
  links:
   - redis
  command: celery -A speakeazy.taskapp worker -l INFO

celerybeat: # assigns tasks to workers I think
  build: .
  user: django
  env_file: .env
  links:
    - redis
  command: celery -A speakeazy.taskapp beat -l INFO
